"""Пороги и шаги рекомендательной системы (упражнение 1)."""

TARGET_SUCCESS_MIN = 0.65
TARGET_SUCCESS_MAX = 0.85
TARGET_SUCCESS = 0.75

EWMA_ALPHA = 0.35
HISTORY_SESSIONS = 5
HYSTERESIS_COUNT = 2

APPLE_STEP = 2
SECONDS_STEP = 1

APPLE_COUNT_MIN = 3
APPLE_COUNT_MAX = 30
SECONDS_PER_APPLE_MIN = 3
SECONDS_PER_APPLE_MAX = 20

DEFAULT_APPLE_COUNT = 8
DEFAULT_SECONDS_PER_APPLE = 10

MIN_VALID_SESSIONS = 1
